<?php

namespace Bordeux\LanguageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LanguageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageTranslationRepository extends EntityRepository
{
}
