<?php

namespace Bordeux\LanguageBundle\Repository;

use Bordeux\LanguageBundle\Entity\Language;
use Doctrine\ORM\EntityRepository;

/**
 * LanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LanguageRepository extends EntityRepository
{

    /**
     * @author Krzysztof Bednarczyk
     * @param string $locale
     * @return Language|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getFromLocale($locale)
    {
        return $this->createQueryBuilder("l")
            ->leftJoin("l.alias", "a")
            ->andWhere("l.locale = :locale")->setParameter(":locale", $locale)
            ->getQuery()
            ->useQueryCache(true)
            ->useResultCache(true, 3600, "language_{$locale}")
            ->getOneOrNullResult();
    }
}
